server:
  port: ${SERVER_PORT:2333}
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "spsearch:%QUERY%"
      - "ymsearch:%QUERY%"
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      spotify: ${LAVASRC_SPOTIFY_ENABLED:false}
      yandexmusic: ${LAVASRC_YANDEX_MUSIC_ENABLED:false}
      youtube: false
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID:}
      clientSecret: ${SPOTIFY_CLIENT_SECRET:}
    yandexMusic:
      accessToken: ${YANDEX_MUSIC_ACCESS_TOKEN:}

lavalink:
  server:
    password: "${LAVALINK_SERVER_PASSWORD:change-me-local}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    resumingEnabled: true
    resumeTimeout: 300
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      snapshot: false

logging:
  level:
    root: INFO